# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
serve: true # hmmm added to fix issue
title: myjekyllblog # Your awesome title
email: ugajin@zoho.com # your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
description: >
  This is a multi-line description located in _config.yml. Its content will be rendered in the page template  footer, as well as in the HTML document head meta markup (used for Google search results), and in the RSS feed.xml site description.
baseurl: "/myjekyllblog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
